PelisBlog/Peliculas/urls.py
from . import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('peliculas/', views.lista_peliculas, name='ultimos_estrenos'),
    path('ficha_pelicula/<id>', views.ficha_pelicula, name='ficha_pelicula'),
    path('compra_exitosa', views.compra_exitosa, name='compra_exitosa'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PelisBlog/PelisBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="inicio"),
    path('peliculas', views.peliculas, name="peliculas"),
    path('login', views.login_succes, name="login"),
    path('logout/', views.logout_succes, name='logout'),
    path('compras/', views.compras, name='compras'),
    path('peliculas/', include('Peliculas.urls')),
    path('registro', views.registro, name="registro"),
    path('orden_de_compra/<id>', views.orden_de_compra, name="orden_de_compra"),
    path('ordenes_de_compras/', views.ordenes_de_compras, name="ordenes_de_compras"),
    path('peril_usario', views.perfil, name='perfil'),
    
    path('reportes/', views.reportes, name="reportes"),
    path('exportar/exportar_reporte_completo/', views.exportar_reporte_completo, name="exportar_reporte_completo"),
    path('exportar/exportar_reporte_fecha/', views.exportar_reporte_fecha, name="exportar_reporte_fecha"),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PelisBlog/Peliculas/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Peliculas(models.Model):
    foto = models.ImageField(upload_to='images/')
    nombre = models.CharField(max_length=150)
    descripcion = models.TextField()
    precio = models.IntegerField()
    fecha = models.DateTimeField(auto_now_add=True)

def __str__(self):
    return self.nombre

class PerfilUsuario(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rut = models.CharField(max_length=40, default="Sin Rut", null=True, blank=True)
    direccion = models.CharField(max_length=100, null=False, blank=False, verbose_name='direccion')
    comuna = models.CharField(max_length=100, null=False, blank=False, verbose_name='comuna')
    telefono = models.IntegerField()
    region = models.CharField(max_length=100, null=False, blank=False, verbose_name='region')
    
    def __str__(self) -> str:
        return f"{self.user.username}"

class Factura(models.Model):
    codigo_factura = models.AutoField(primary_key=True)
    usuario = models.ForeignKey(PerfilUsuario, on_delete=models.CASCADE)
    nombre_producto = models.CharField(max_length=90, null=True)
    monto_producto = models.IntegerField(default=1, blank=True, null=True)
    precio_producto = models.IntegerField()
    fecha_factura = models.DateTimeField(auto_now=True)
    estado_factura = models.CharField(max_length=40 ,default="Pendiente", null=True, blank=True)
    

PelisBlog/Peliculas/views.py
from django.shortcuts import render, get_object_or_404, redirect
from Peliculas.models import Peliculas, PerfilUsuario, Factura

# Create your views here.

def lista_peliculas(request):
    peliculas = Peliculas.objects.all()
    return render(request, 'peliculas.html', {'peliculas':peliculas})

def ficha_pelicula(request, id):
    
    pelicula = Peliculas.objects.get(id=id)
    if request.method == 'POST':
        if request.user.is_authenticated:
            if not request.user.is_staff:
                user = request.user
                
                perfil = PerfilUsuario.objects.get(user=user)
                
                usuario = perfil
                
                nombre_pelicula = pelicula.nombre
                precio_pelicula = pelicula.precio
                cantidad_pelicula = request.POST['cantidad']
                
                factura = Factura.objects.create(usuario=usuario, nombre_producto=nombre_pelicula, monto_producto=cantidad_pelicula, precio_producto=precio_pelicula)
                return redirect ('orden_de_compra', factura.pk)
            else:
                return redirect ('ficha_pelicula', id = pelicula.pk)
        else:
            return redirect ('ficha_pelicula', id = pelicula.pk)
            
    return render(request, 'ficha_pelicula.html', {'pelicula':pelicula})

def compra_exitosa(request):
    return render(request, 'compra_exitosa.html')

def compras(request):
    persona = PerfilUsuario.objects.all()
    if request.method == "POST":
        valor_id = request.POST['factura_id']
        factura_cambio = request.POST['estado']
        
        obtener_factura = get_object_or_404(Factura, pk=valor_id)
        obtener_factura.estado_factura = factura_cambio
        
        obtener_factura.save()
    return render(request, 'compras.html', {'persona':persona})

PelisBlog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}<title>PelisBlog</title>{% endblock title %}
    {% block css %}<link rel="stylesheet" href="{% static 'css/style.css' %}">{% endblock css %}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="shortcut icon" href="{% static 'img/camara2.png' %}" type="image/x-icon">
    
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Libre+Franklin:ital,wght@1,700&display=swap" rel="stylesheet">
<link rel="preconnect" href="https://fonts.googleapis.com">
<!-- <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Libre+Franklin:ital,wght@0,600;1,700&display=swap" rel="stylesheet"> -->
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</head>
<body>
    <div class="container-fluid">
    {% block nav %}
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <ul  class="navbar-nav">
            <li class="nav-item"><img class="logo" src="{% static 'img/camara2.png' %}" alt="Logo"></li>
            <li class="nav-item"><strong></strong><a  href="{% url 'inicio' %}" class="navbar-brand">PELIS <br> BLOG</a></strong></li> 

            {% if not user.is_authenticated %}
            <li class="nav-item"><a class="nav-link" href="{% url 'login' %}"> <h5 style="color: White;"> Iniciar Sesión </h5></a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'ultimos_estrenos' %}"><h5 style="color: White;">Peliculas</h5></a></li>
            {% endif %}

            {% if user.is_authenticated and user.is_staff %}

            {% endif %}

            {% if user.is_authenticated %}
            <li class="nav-item"><a class="nav-link" href="{% url 'ultimos_estrenos' %}"><h5 style="color: White;">Peliculas</h5></a></li>
            <li class="nav-item"> <a class="nav-link" href="{% url 'compras' %}"><h5 style="color: White;">Compras</h5></a> </li>
            <li class="nav-item"> <a class="nav-link"href="{% url 'logout' %}"><h5 style="color: White;">Cerrar sesión</h5></a> </li>
            {% if not user.is_staff %}
            <li class="nav-item"><h5 class="nav-link" style="color: White;">Hola Cliente</h5></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'perfil' %}"><h5 style="color: White;">{{ request.user }}</h5></a></li>
            {% else %}
            <li class="nav-item"><h5 class="nav-link" style="color: White;">Hola Administrador</h5></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'ordenes_de_compras' %}"><h5 style="color: White;">Ordenes</h5></a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'reportes' %}"><h5 style="color: White;">Reportes</h5></a></li>
            {% endif %}
            
            {% endif %}
        </ul>
    </nav>
    {% endblock nav %}
    </div>
    {% block content %}
    {% endblock content %}
    {% block js %}{% endblock js %}
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" 
    integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" 
integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
</body>
</html>

PelisBlog/templates/cambio.html
benja miamor

Hola Cristobal

Hola Cristobal 2

PelisBlog/templates/compra_exitosa.html
{% extends "base.html" %}
{% load static %}
{% block css %} <link rel="stylesheet" href="{% static 'css/compra_exitosa.css' %}">{% endblock css %}
{% block content %}
<div class="container">
    <h1 class="compra_exitosa">Compra Exitosa</h1>
    <div class="datos-compra">
        <p>Fecha: <span id="fecha"></span></p>
        <p>Nombre: <span id="nombre"></span></p>
        <p>Precio: <span id="precio"></span></p>
    </div>
</div>
{% endblock content %}
{% comment %} {% block js %} <script src="{% static 'js/recuperar_datos.js' %}"></script>{% endblock js %} {% endcomment %}

PelisBlog/templates/compras.html
{% extends "base.html" %}
{% load static %}
{% block css %} <link rel="stylesheet" href="{% static 'css/compra_exitosa.css' %}">{% endblock css %}
{% block content %}
<div class="container">
    <h1 class="compra_exitosa">Compras</h1>
    {% for persona in persona %}
    <table class="table">
        <thead>
            <tr>
                <th>Fecha</th>
                <th>Pelicula</th>
                <th>Precio</th>
                <th>Dirección</th>
                <th>Region</th>
                <th>Comuna</th>
                <th>Cliente</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td id="fecha">Fecha1</td>
                <td id="nombre">Nombre1</td>
                <td id="precio">Precio1</td>
                <td>{{ persona.direccion}}</td>
                <td>{{ persona.region}}</td>
                <td>{{ persona.comuna}}</td>
                <td>{{ persona.user.first_name }} {{ persona.user.last_name }}</td>
            </tr>
            <tr>
                <td id="fecha">Fecha2</td>
                <td id="nombre">Nombre2</td>
                <td id="precio">Precio2</td>
                <td>{{ persona.direccion}}</td>
                <td>{{ persona.region}}</td>
                <td>{{ persona.comuna}}</td>
                <td>{{ persona.user.first_name }} {{ persona.user.last_name }}</td>
            </tr>
            <!-- Agrega más filas según sea necesario -->
        </tbody>
    </table>
    {% endfor %}
</div>
{% endblock content %}
{% block js %} <script src="{% static 'js/recuperar_datos.js' %}"></script>{% endblock js %}

PelisBlog/templates/ficha_pelicula.html
{% extends "base.html" %}
{% load static %}
{% block css %}<link rel="stylesheet" href="{% static 'css/ficha_peli.css' %}">{% endblock css %}
{% block content %}
<div class="container">
    <div class="peliculas">
        <div class="pelicula">
                <img class="img1" src="{{ pelicula.foto.url }}" alt="{{ pelicula.nombre }}">
            <div class="info-peli">
                <p>{% now "DATETIME_FORMAT" %}</p>
                <p class="id-peli">{{ pelicula.id }}</p>
                <h1 class="nombre-peli">{{ pelicula.nombre }}</h1>
                <h5 class="precio">${{ pelicula.precio }}</h5>
                <form action="#" method="POST">
                    {% csrf_token %}
                    <label for="Cantidad">Cantidad: 
                        <input type="number" name="cantidad" id="cantidad">
                    </label>
                    <button>Comprar</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

PelisBlog/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="texto-btn">
    <strong><h1 class="texto_principal">¡ENTERATE DE LAS <br> PELICULAS DEL <br> MOMENTO!</h1></strong>
    <div class="btn">
        <a class="boton" href="{% url 'ultimos_estrenos' %}">Comenzar</a>
    </div>
</div>
{% endblock content %}

PelisBlog/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div id="login">
    <div class="container">
        <div id="login-row" class="row justify-content-center align-items-center">
            <div id="login-column" class="col-md-6">
                <div class="login-box col-md-12">
                    <form id="login-form" class="form" action="" method="post">
                        {% csrf_token %}
                        <h3 class="text-center text-info">Inicio de sesion</h3>
                        <div class="form-group">
                            <label for="username" class="text-info">Usuario:</label><br>
                            <input type="text" name="username" id="username" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="password" class="text-info">Contraseña:</label><br>
                            <input type="password" name="password" id="password" class="form-control">
                        </div>
                        <div class="form-group">
                        <br>
                            <center>
                                <input type="submit" name="submit" class="btn btn-info btn-md" value="Ingresar">
                            </center>
                        </div>
                        <div id="register-link" class="text-right">
                            <a href="{% url 'registro' %}" class="text-info">Registrate Aqui</a>
                        </div>
                        <br>
                        {% if mesg %}
                        <div id="form_message" class="alert alert-danger" role="alert" style="text-align: center;">{{ mesg }}</div>
                        {% endif %}
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<style> 
    body {
    background-image: linear-gradient(to left top, #17a2b8, #14abc4, #12b3d1, #11bcde, #12c5eb);
    height: 100vh;
    }
    #login .container #login-row #login-column .login-box {
    margin-top: 120px;
    max-width: 600px;
    height: 320px;
    border: 1px solid #9C9C9C;
    background-image: linear-gradient(to bottom, #aec1c3, #a9b5b7, #bcc5c6, #cfd5d5, #e3e5e5);
    }
    #login .container #login-row #login-column .login-box #login-form {
    padding: 20px;
    }
    #login .container #login-row #login-column .login-box #login-form #register-link {
    margin-top: -85px;
    }
</style>

{% endblock content %}

PelisBlog/templates/orden_de_compra.html
{% extends "base.html" %}
{% load static %}
{% block css %}<link rel="stylesheet" href="{% static 'css/ficha_peli.css' %}">{% endblock css %}
{% block content %}
<div class="fondo"> 
    <center><h2 class="titulo">Mi orden de compra</h2></center>
    <div class="producto-singular">
        <!-- Productos aquí -->
        {% for fa in factura %}
        <table>
            <thead>
                <tr>
                    <th>
                        Usuario y Dirección de envio
                    </th>
                    <th>
                        Codigo de orden
                    </th>
                    <th>
                        Datos del Producto
                    </th>
                    <th>
                        Fecha
                    </th>
                    <th>
                        Monto Total
                    </th>
                    <th>
                        Estado
                    </th>
                    {% if fa.estado_factura == 'Facturado' %}
                    <th>
                        Estado Envio
                    </th>
                    {% endif %}
                    {% if user.is_authenticated and user.is_staff %}
                    <th>
                        Opcion
                    </th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        <div>
                            <span class="negrita">Usuario:</span> {{ fa.usuario.user }}
                        </div>
                        <div>
                            <span class="negrita">Dirección a enviar:</span>
                            {{ fa.usuario.direccion }}, {{ fa.usuario.comuna }} {{ fa.usuario.region }}
                        </div>
                    </td>
                    <td>
                        {{ fa.codigo_factura }}
                    </td>
                    <td>
                        <div>
                            <span class="negrita">Nombre: </span> {{ fa.nombre_producto }}
                        </div>
                        <div>
                            <span class="negrita">Precio: </span>{{ fa.precio_producto }}
                        </div>
                        <div>
                            <span class="negrita">Cantidad: </span>{{ fa.monto_producto }}
                        </div>
                    </td>
                    <td>
                        {{ fa.fecha_factura }}
                    </td>
                    <td>
                        <div>
                            <span class="negrita">Neto: </span>{{ monto_neto }}
                        </div>
                        <div>
                            <span class="negrita">IVA(19%): </span>{{ monto_iva }}
                        </div>
                        <div class="resaltado">
                            <span class="negrita">Total: </span> {{ monto_total }}
                        </div>
                    </td>
                    <td>
                        {{ fa.estado_factura }}
                    </td>
                    {% if fa.estado_factura == 'Facturado' %}
                    <td>
                        Enviado
                    </td>
                    
                    {% endif %}
                    {% if user.is_authenticated and user.is_staff %}
                    <td>
                        <button>
                            Editar
                        </button>
                    </td>
                    {% endif %}
                </tr>
            </tbody>
        </table>
        {% endfor %}
    </div>
    {% if estado_factura == "Pendiente" %}
    <div class="footer-factura">
        {% comment %} Esta orden de compra se encuentra actualmente por validación, lo puedes verificar en tu perfil cuantas veces quieras. {% endcomment %}
    </div>
    <div class="footer-factura2">
        {% comment %} Cuando tu orden de compra cambie de estado a "Aceptado", podras observar la siguiente fase, que es el estado de envio de tu producto. {% endcomment %}
    </div>
    {% elif estado_factura == "Facturado" %}
    <div class="footer-factura">
        {% comment %} ¡Exelente, Tu orden de compra se Aprobo!  {% endcomment %}
    </div>
    <div class="footer-factura2">
        {% comment %} Tu orden de compra sera despachado por nuestros Agentes, te llamaremos cuando estemos cerca la dirección de envio que indicaste al momento de registarte. {% endcomment %}
    </div>
    {% else %}
    <div class="footer-factura">
        {% comment %} ¡Lo sentimos, tu orden de compra fue rechazada por nuestros Agentes! {% endcomment %}
    </div>
    {% endif %}
</div>

<style>
    th,  td{
        border: 3px solid black;
        width: 200px;
        text-align: center;
    }
    th{
        height: 100px;
        font-size: 20px;
    }
    td{
        height: 300px;
        font-size: 25px;
    }
    .producto-singular{
        display: flex;
        align-items: center;
        align-content: center;
        justify-content: center;
        flex-direction: row;
        flex-wrap: nowrap;
    }
    .resaltado{
        background-color: yellow;
    }
.titulo{
    margin-bottom: 20px;
    margin-top: 180px;
    font-size: 70px;
}
.footer-factura{
    margin-top: 50px;
    text-align: center;
}
.footer-factura2{
    text-align: center;
}
tbody tr td:first-child{
    width: 300px;
}
tbody tr td:nth-child(3){
    width: 300px;
}
.negrita{
    font-weight: bold;
}
.fondo{
    background-color: #ffff;
}
</style>

{% endblock %}

PelisBlog/templates/ordenes_de_compras.html
{% extends "base.html" %}
{% load static %}
{% block css %}<link rel="stylesheet" href="{% static 'css/ficha_peli.css' %}">{% endblock css %}
{% block content %}
    <center><h2 class="titulo">Ordenes de Compra</h2></center>
    <div class="producto-singular">
        <!-- Productos aquí -->
        {% for fa in factura %}
        <table>
            <thead>
                <tr>
                    <th>
                        Usuario
                    </th>
                    <th>
                        Codigo
                    </th>
                    <th>
                        Datos Producto
                    </th>
                    <th>
                        Fecha
                    </th>
                    <!-- <th>
                        Monto Total
                    </th> -->
                    <th>
                        Estado
                    </th>
                    {% if user.is_authenticated and user.is_staff %}
                    <th>
                        Opcion
                    </th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        {{ fa.usuario.user }}
                    </td>
                    <td>
                        {{ fa.codigo_factura }}
                    </td>
                    <td>
                        <div>
                            Nombre: {{ fa.nombre_producto }}
                        </div>
                        <div>
                            Precio: {{ fa.precio_producto }}
                        </div>
                        <div>
                            Cantidad: {{ fa.monto_producto }}
                        </div>
                    </td>
                    <td>
                        {{ fa.fecha_factura }}
                    </td>
                    <!-- <td>
                        <div>
                            Neto: {{ fa.monto_neto }}
                        </div>
                        <div>
                            IVA(19%): {{ monto_iva }}
                        </div>
                        <div class="resaltado">
                            Total: {{ monto_total }}
                        </div>
                    </td> -->
                    <td>
                        {{ fa.estado_factura }}
                    </td>
                    <td>
                        <button class="editar-btn" data-toggle="modal" data-target="#editarModal" data-id="{{ fa.codigo_factura }}">
                            Editar {{ fa.codigo_factura }}
                        </button>
                    </td>
                </tr>
            </tbody>
        </table>
        {% endfor %}
    </div>
    {% if estado_factura == "Pendiente" %}
    <div class="footer-factura">
        Esta orden de compra se encuentra actualmente por validación, lo puedes verificar en tu perfil cuantas veces quieras 😊
    </div>
    {% else %}
    <div class="footer-factura">
        ¡Exelente, Tu orden se Aprobo!
    </div>
    {% endif %}
</div>
<div class="modal fade centrado" id="editarModal" tabindex="-1" role="dialog" aria-labelledby="editarModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editarModalLabel">Editar Estado de orden</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="ojo">
                    ¡OJO!, los estados de ordenes solo deben contar con 3 estados : "Facturado", "Pendiente", "Rechazado"
                </div>
                <form class="form-mensaje" id="editarForm" method="POST" action="" enctype="multipart/form-data">
                    {% csrf_token  %}
                    <label for="estado">Estado:
                        <input type="text" name="estado" id="estado">
                    </label>
                    <input type="hidden" name="factura_id" id="facturaIdInput" value="">
                    <input type="submit" class="btn btn-primary btnwidth" id="id_guardar" value="Guardar">
                </form>
            </div>
        </div>
    </div>
</div>
<style>
    th,  td{
        border: 3px solid black;
        width: 200px;
        text-align: center;
    }
    th{
        height: 100px;
        font-size: 20px;
    }
    td{
        height: 300px;
        font-size: 25px;
    }
    .producto-singular{
        display: flex;
        align-items: center;
        align-content: center;
        justify-content: center;
        flex-direction: column;
        flex-wrap: nowrap;
        gap: 10px;
    }
    .resaltado{
        background-color: yellow;
    }
.titulo{
    margin-bottom: 20px;
    margin-top: 180px;
    font-size: 70px;
}
.footer-factura{
    margin-top: 50px;
    text-align: center;
}
tbody tr td:nth-child(3){
    width: 300px;
}
.centrado{
    margin-top: 300px;
}
.ojo{
    text-align: center;
    font-size: 17px;
    font-weight: bold;
    margin-top: 3px;
    margin-bottom: 20px;
}
</style>

    <!-- Bootstrap JS con Popper.js y jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $('.editar-btn').on('click', function () {
                var facturaId = $(this).data('id');
                // Mostrar el ID en la consola    
                // Abrir el modal
                $('#editarModal').modal('show');
    
                // Cambiar el valor del campo oculto después de que el modal se haya mostrado
                $('#editarModal').on('shown.bs.modal', function () {
                    $('#facturaIdInput').val(facturaId);
                });
            });
        });
    </script>

{% endblock %}

PelisBlog/templates/peliculas.html
{% extends 'base.html' %}
{% load static %}
{% block css %}<link rel="stylesheet" href="{% static 'css/peliculas.css' %}">{% endblock css %}
{% block content %}
<h1 class="ultimos-estrenos">Ultimos Estrenos</h1>
{% for pelicula in peliculas %}
<div class="container">
    <div class="peliculas">
        <div class="pelicula">
            <a href="{% url 'ficha_pelicula' pelicula.id %}"><img src="{{ pelicula.foto.url }}" alt="{{ pelicula.nombre }}">
            <h1 class="nombre-peli">{{ pelicula.nombre }}</h1></a>
        </div>
    </div>
</div>
{% endfor %}
{% endblock content %}

PelisBlog/templates/registro.html
{% extends "base.html" %}
{% load static %}
{% block css %}<link rel="stylesheet" href="{% static 'css/registro.css' %}">{% endblock css %}
{% block content %}
  <h2 style="text-align: center;">Registro</h2>
  <form method="post" class="formulario">
    {% csrf_token %}
    <div class="campo">
      <label for="id_usuarname">Usuario:</label>
      <input name="username" type="text" autofocus required id="id_usuarname" class="form-control">
    </div>
    <div class="campo">
      <label for="id_first_name">Nombre: </label>
      <input name="first_name" type="text" id="id_first_name" class="form-control">
  </div>
  <div class="campo">
    <label for="id_rut" class="letra-piola" >Rut: </label>
    <input name="rut" type="text" id="id_rut" class="form-control">
  </div>
</div>
<div class="campo">
  <label for="id_last_name" class="letra-piola" >apellidos: </label>
  <input name="last_name" type="text" id="id_last_name" class="form-control">
</div>
    <div class="campo">
      <label for="id_direccion" class="letra-piola" >Dirección: </label>
      <input name="direccion" type="text" required id="id_direccion" class="form-control">
  </div>
    <div class="campo">
      <label for="id_telefono">Teléfono:</label>
      <input name="telefono" type="number" required id="id_telefono" class="form-control">
    </div>
    <div class="campo">
      <label for="id_comuna">Comuna:</label>
      <input name="comuna" type="text" required id="id_comuna" class="form-control">
    </div>
    <div class="campo">
      <label for="id_region">Región:</label>
      <input name="region" type="text" required id="id_region" class="form-control">
    </div>
    <div class="campo">
      <label for="id_password1" class="letra-piola" >Contraseña: </label>
      <input name="password1" type="password" autocomplete="new-password" required id="id_password1" class="form-control">
  </div>
    <div class="campo">
      <label for="id_password2" class="letra-piola" >Repetir Contraseña: </label>
      <input name="password2" type="password" autocomplete="new-password" required id="id_password2" class="form-control">
  </div>
    <button type="submit">Registrarse</button>
  </form>
{% endblock %}